name: rustdoc
on:
  push:
   branches:
   - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    if: github.repository == 'tavimori/fogcore'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src
    
    - uses: Swatinem/rust-cache@v2
    - uses: cargo-bins/cargo-binstall@main

    - name: Build Documentation
      run: cargo doc --all --no-deps

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build and move wasm package
      run: | 
        wasm-pack build --target web --features wasm --no-default-features
        mkdir -p ./target/doc/pkg
        cp -R ./pkg/* ./target/doc/pkg/

    - name: Create demo folder and move static files
      run: |
        mkdir -p ./target/doc/demo
        cp -R ./static/* ./target/doc/demo/

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true