name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # For wgpu rendering
    - name: Install Mesa for software rendering
      run: sudo apt-get install -y mesa-utils libgl1-mesa-dri

    - uses: Swatinem/rust-cache@v2
    - uses: cargo-bins/cargo-binstall@main
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Compress test outputs
      if: always()
      run: |
        cd tests
        tar -czf outputs.tar.gz outputs/
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-outputs
        path: tests/outputs.tar.gz
        retention-days: 7
